
$(function(){if(typeof refreshTimeout!="undefined"&&$('#activityStreamContainer').length>0&&(!$.browser.msie||parseInt($.browser.version)>7)){setTimeout("retrieveActivity(false)",refreshTimeout);}
$('.sm-more-activity .sm-button').click(function(e){e.preventDefault();$('.sm-more-activity').hide();retrieveActivity(true);});if(typeof welcome!="undefined"){trackEvent("signup/success");welcomeMessage();}
$('.open-welcome').click(function(e){e.preventDefault();welcomeMessage();});loadMarketMessages();$("#activityStreamContainer").delegate('form.jsNewsVoteForm',"submit",function(e){e.preventDefault();});$('form.jsWidgetNewsVoteForm').each(function(e){voteForm=$(this,e);likeDiv=voteForm.find('div');likedButton=voteForm.find('button.jsNewsVoteLiked');votedDown=voteForm.find('button.jsNewsVoteDown');if(votedDown.length){votedDown.html('');likeDiv.html(likeDiv.html().replace('|',''));}else if(likedButton.length){likeDiv.append('<span class="quiet">Liked</span>');}else{likeDiv.append('<a class="jsNewsVoteUp sm-link">Like</a>');}});$('form.jsWidgetNewsVoteForm').click(function(e){e.preventDefault();});$('a.jsNewsVoteUp').click(function(e){voteUpButton=$(this,e);voteNewsUp(voteUpButton);});$("#activityStreamContainer").delegate('button.jsNewsVoteUp',"click",function(e){voteUpButton=$(this,e);voteNewsUp(voteUpButton);});$("#activityStreamContainer").delegate('button.jsNewsVoteDown',"click",function(e){voteDownButton=$(this,e);voteForm=voteDownButton.closest('form.jsNewsVoteForm');postedData=voteForm.serialize();postedData+='&voteValue=DOWN';$.post(getContextualAjaxUrl(voteForm.getAction()),postedData,function(data){newsDiv=voteForm.closest('.sm-activity-event ');newsDiv.fadeOut('slow',function(){newsDiv.html(data.json.message).fadeIn();});smid=$('INPUT[name=smid]',voteForm).val();$('INPUT[value='+smid+']').each(function(e){localSmidInput=$(this,e);widgetVoteForm=localSmidInput.closest('form.jsWidgetNewsVoteForm');if(widgetVoteForm.length){widgetVoteUpButton=widgetVoteForm.find('a.jsNewsVoteUp');widgetVoteUpButton.html('');likeDiv=widgetVoteForm.find('div');likeDiv.html(likeDiv.html().replace('|',''));}});trackEvent('activity/news/'+$('INPUT[name=companyName]',voteForm).val()+'/votedown/'+$('INPUT[name=title]',voteForm).val());});});});document.write('<style type=\"text/css\">.jsWidgetNewsVoteUpButton{display:none;}</style>');function voteNewsUp(voteUpButton){if(voteUpButton.hasClass('jsNewsVoteLiked')){return;}
voteForm=voteUpButton.closest('form.jsNewsVoteForm');postedData=voteForm.serialize();postedData+='&voteValue=UP';$.post(getContextualAjaxUrl(voteForm.getAction()),postedData,function(data){smid=$('INPUT[name=smid]',voteForm).val();$('INPUT[value='+smid+']').each(function(e){localSmidInput=$(this,e);localVoteForm=localSmidInput.closest('form.jsNewsVoteForm');localVoteUpButton=localVoteForm.find('button.jsNewsVoteUp');if(localVoteUpButton.length==0){localVoteUpButton=localVoteForm.find('a.jsNewsVoteUp');likeNewsEvent(localVoteForm,localVoteUpButton,true);}
else{likeNewsEvent(localVoteForm,localVoteUpButton,false);}});trackEvent('activity/news/'+$('INPUT[name=companyName]',voteForm).val()+'/voteup/'+$('INPUT[name=title]',voteForm).val());});}
function loadMarketMessages(){if($('#marketMessagesContainer').length>0){$.getJSON('/m/notifications/markets',function(response){if(response.json!=undefined){$('#marketMessagesContainer').parent().hide();}else{$('#marketMessagesContainer').parent().show();$('#marketMessagesContainer').html(response.html[0].toString());}});}}
function likeNewsEvent(voteForm,voteUpButton,isWidget)
{voteCountElement=voteForm.find('.jsVoteCount');if($.trim(voteCountElement.text())=="--"){voteCountElement.html(1);}
else{voteCount=parseInt(voteCountElement.text());voteCountElement.html(voteCount+1);}
if(isWidget){voteUpButton.replaceWith('<span class="quiet">Liked</span>');}
else{voteUpButton.addClass('jsNewsVoteLiked');voteUpButton.html('Liked');}
voteForm.find('button.jsNewsVoteDown').css('visibility','hidden');}
function retrieveActivity(more){if($('#activityStreamContainer').length>0){if(more){eventCard=$('#activityStreamContainer .sm-activity-event:last');}else{eventCard=$('#activityStreamContainer .sm-activity-event:first');}
$('#activityLoading').show();if(eventCard.length){adjustTs=(more)?-1:1;ts=Number(eventCard.attr("time"))+adjustTs;events="true";}else{ts="0";events="false";}
parameter=(more)?'beforeTs='+ts:'afterTs='+ts;urlArray=location.href.split('?');url=urlArray[0];if(url.indexOf('#!news')>=0||url.indexOf('/news')>=0||url.indexOf('#!activity')>=0||url.indexOf('/activity')>=0){url=url.replace('#!','/')+'/more';}
$.get(getContextualAjaxUrl(url)+"?"+parameter+"&events="+events,function(response){if(response.length>0){if(events=="true"){if(more){$('#activityStreamContainer').append(response);$('.sm-more-activity').show();}else{$('#activityStreamContainer').prepend(response);}}else{$('#activityStreamContainer').html(response);}
addTimeago();}else if(more){$('.sm-more-activity').hide();}
setTimeout("fadeMessage()",500);});if(!more)setTimeout("retrieveActivity()",refreshTimeout);}}
function fadeMessage(){$('#activityLoading').fadeOut("slow");}
function welcomeMessage(){$.getJSON(getContextualAjaxUrl("/welcome"),function(response){message(response.html[0].toString(),"info",750);$('.close-welcome').click(function(e){e.preventDefault();errors.close();});});}
function companyChooseAddAutocomplete(companyNameFieldId,companySmidFieldId,onlyExistingCompanies,onlyInvestable,includeHidden,includeSmOnly){if(typeof onlyExistingCompanies=='undefined')onlyExistingCompanies=false;if(typeof onlyInvestable=='undefined')onlyInvestable=false;if(typeof includeHidden=='undefined')includeHidden=false;if(typeof includeSmOnly=='undefined')includeSmOnly=false;$(companyNameFieldId).autocomplete({selectFirst:true,source:function(request,response){$.ajax({url:_URL['organization-autocomplete'],dataType:'json',data:{q:request.term.toLowerCase()+'*',limit:15,onlyInvestable:onlyInvestable,includeHidden:includeHidden,includeSmOnly:includeSmOnly},success:function(data){if(!onlyExistingCompanies){newCompany={name:'Add "'+request.term+'" as a new organization',value:request.term,slug:'_add',type:'company'};data.data.push(newCompany);}
response($.map(data.data,function(item){return{label:item.name,value:(typeof item.value=='undefined')?item.name:item.value,slug:item.slug,type:item.type}}));},error:function(er){displayAjaxError=false;}})},select:function(event,ui){if(ui.item){if(ui.item.type=='organization'&&(companyNameFieldId.indexOf('bid')>=0||companyNameFieldId.indexOf('holding')>=0)){message('<p>We can not currently accept Holdings, Listings or Bids for '+ui.item.value+'</p><p>Please try selecting a different company</p>');$(companyNameFieldId).val('');$(companySmidFieldId).val('');return false;}else{$(companySmidFieldId).val(ui.item.slug);if(ui.item.slug=='_add'){$(companyNameFieldId).val(ui.item.value);if(typeof ACCustomSelectHandler!='undefined')ACCustomSelectHandler(ui.item,companySmidFieldId,companyNameFieldId,'addCompanyForm_name');return false;}
if(typeof ACCustomSelectHandler!='undefined')ACCustomSelectHandler(ui.item,companySmidFieldId,companyNameFieldId,'addCompanyForm_name');}}},open:function(){$(companySmidFieldId).removeAttr('value');$('#addCompany_name').removeAttr('value');$(this).removeClass('ui-corner-all').addClass('ui-corner-top');},close:function(){if($(companyNameFieldId).val().length==0){$(companySmidFieldId).removeAttr('value');$('#addCompany_name').removeAttr('value');}else if($(companySmidFieldId).val().length==0&&$('#addCompany_name').length&&$('#addCompany_name').val().length==0){$(companyNameFieldId).removeAttr('value');}
$(this).removeClass('ui-corner-top').addClass('ui-corner-all');},delay:80,minLength:1});$(companyNameFieldId).change(function(e){toggleChangeCompany(companyNameFieldId,companySmidFieldId);});toggleChangeCompany(companyNameFieldId,companySmidFieldId);}
function toggleChangeCompany(companyNameFieldId,companySmidFieldId){if($(companyNameFieldId).val().length==0){$(companySmidFieldId).removeAttr('value');$('#addCompany_name').removeAttr('value');}else if($(companySmidFieldId).val().length==0&&$('#addCompany_name').length>0&&$('#addCompany_name').val().length==0){$(companyNameFieldId).removeAttr('value');}}
$(function(){triggers=$("#profileConnectOverlay").overlay({api:true,top:100,onBeforeLoad:function(el){o=this;link=getContextualAjaxUrl(connectButton.attr('href'));$.get(link,function(data){o.getOverlay().html(data.toString());$.include(contextPath+"static/javascript/m/invite.js");trackAjaxPage(link);});},onLoad:function(el){$('.close-overlay').click(function(e){e.preventDefault();triggers.close();});},onClose:function(el){this.getOverlay().html("");},mask:{color:'#000',loadSpeed:200,opacity:0.42},closeOnClick:true,fixed:false,load:false});$('.profileConnect').live('click',function(e){e.preventDefault();connectButton=$(this,e);if(!connectButton.hasClass("invite-pending")){triggers.load();}});$('.removeConnectionLink').click(function(e){e.preventDefault();link=$(this,e);containerId=link.attr('rel');href=link.attr('href');container=$.fn.makeOverlay(containerId);$.getJSON(getContextualAjaxUrl(href),function(response){container.getOverlay().find('.select-content').html(response.html[0].toString());container.getOverlay().find('FORM').submit(function(e){e.preventDefault();form=$(this,e).closest('FORM');data=form.serialize();$.post(getContextualAjaxUrl(form.getAction()),data,function(response){container.getOverlay().find('.select-content').html(response.json.message);setTimeout(function(){container.close();window.location.reload();},2000);});});container.load();});});$('.bbq-content').delegate('.acceptInvitation, .ignoreInvitation',"submit",function(el){form=$(this,el);if(respondToInvitation(form)){el.preventDefault();}});$('.acceptInvitation, .ignoreInvitation').submit(function(el){form=$(this,el);if(respondToInvitation(form)){el.preventDefault();}});$('.inviteConnectionLink').click(function(e){e.preventDefault();link=$(this,e);containerId=link.attr('rel');href=link.attr('href');container=$.fn.makeOverlay(containerId);$.get(getContextualAjaxUrl(href),function(response){container.getOverlay().find('.select-content').html(response);$('.invite-connections-form').submit(function(f){f.preventDefault();form=$(this,f);data=form.serialize();$.post(getContextualAjaxUrl(form.attr("action")),data,function(response){responseMessage=response.json.code.toString();container.getOverlay().find('.select-content').html(responseMessage);setTimeout(function(){container.close();if(responseMessage.indexOf("fail")==-1){link.replaceWith('<div class="sm-button sm-invite-pending span-2">Sent</div>');}},8000);});});container.load();})});$('.sm-invite-avatar').error(function(){$(this).hide();});$('FORM.sm-quick-invite').submit(function(el){el.preventDefault();connectButton=$(this,el);data=$(this,el).serialize();targetSmid=$(this,el).find('INPUT[name=to]').val();postAction=getContextualAjaxUrl($(this,el).attr('action'));$.post(postAction,data,function(response){setQuickButtonToPending('Pending');trackEvent("connection/invite/"+targetSmid);});});});function setQuickButtonToPending(pending){connectButton.replaceWith('<div class="sm-r sm-button sm-invite-pending">'+pending+'</div>');}
function respondToInvitation(form){fromUser=form.find(".from").val();display=form.find(".display").val();if(display!="profile"){var data=form.serialize();$.post(getContextualAjaxUrl(form.attr("action")),data,function(response){if(response.json.code.toLowerCase()=="success"){if(display=="dashboard"){newMessage=$("<div>"+response.json.message+" </div>");form.closest(".notification-box").find('.invitation-message').html(newMessage);form.closest(".notification-box").find('.invitation-buttons, .invitation-note').html("");}
else{form.closest(".trust-container").html(response.html[0]);}
trackEvent("connection/accept/"+fromUser);}else{message(response.json.message);}},"json");return true;}
return false;}
(function($,window){'$:nomunge';var undefined,aps=Array.prototype.slice,decode=decodeURIComponent,jq_param=$.param,jq_param_fragment,jq_deparam,jq_deparam_fragment,jq_bbq=$.bbq=$.bbq||{},jq_bbq_pushState,jq_bbq_getState,jq_elemUrlAttr,jq_event_special=$.event.special,str_hashchange='hashchange',str_querystring='querystring',str_fragment='fragment',str_elemUrlAttr='elemUrlAttr',str_location='location',str_href='href',str_src='src',re_trim_querystring=/^.*\?|#.*$/g,re_trim_fragment=/^.*\#/,re_no_escape,elemUrlAttr_cache={};function is_string(arg){return typeof arg==='string';};function curry(func){var args=aps.call(arguments,1);return function(){return func.apply(this,args.concat(aps.call(arguments)));};};function get_fragment(url){return url.replace(/^[^#]*#?(.*)$/,'$1');};function get_querystring(url){return url.replace(/(?:^[^?#]*\?([^#]*).*$)?.*/,'$1');};function jq_param_sub(is_fragment,get_func,url,params,merge_mode){var result,qs,matches,url_params,hash;if(params!==undefined){matches=url.match(is_fragment?/^([^#]*)\#?(.*)$/:/^([^#?]*)\??([^#]*)(#?.*)/);hash=matches[3]||'';if(merge_mode===2&&is_string(params)){qs=params.replace(is_fragment?re_trim_fragment:re_trim_querystring,'');}else{url_params=jq_deparam(matches[2]);params=is_string(params)?jq_deparam[is_fragment?str_fragment:str_querystring](params):params;qs=merge_mode===2?params:merge_mode===1?$.extend({},params,url_params):$.extend({},url_params,params);qs=jq_param(qs);if(is_fragment){qs=qs.replace(re_no_escape,decode);}}
result=matches[1]+(is_fragment?'#':qs||!matches[1]?'?':'')+qs+hash;}else{result=get_func(url!==undefined?url:window[str_location][str_href]);}
return result;};jq_param[str_querystring]=curry(jq_param_sub,0,get_querystring);jq_param[str_fragment]=jq_param_fragment=curry(jq_param_sub,1,get_fragment);jq_param_fragment.noEscape=function(chars){chars=chars||'';var arr=$.map(chars.split(''),encodeURIComponent);re_no_escape=new RegExp(arr.join('|'),'g');};jq_param_fragment.noEscape(',/');$.deparam=jq_deparam=function(params,coerce){var obj={},coerce_types={'true':!0,'false':!1,'null':null};$.each(params.replace(/\+/g,' ').split('&'),function(j,v){var param=v.split('='),key=decode(param[0]),val,cur=obj,i=0,keys=key.split(']['),keys_last=keys.length-1;if(/\[/.test(keys[0])&&/\]$/.test(keys[keys_last])){keys[keys_last]=keys[keys_last].replace(/\]$/,'');keys=keys.shift().split('[').concat(keys);keys_last=keys.length-1;}else{keys_last=0;}
if(param.length===2){val=decode(param[1]);if(coerce){val=val&&!isNaN(val)?+val:val==='undefined'?undefined:coerce_types[val]!==undefined?coerce_types[val]:val;}
if(keys_last){for(;i<=keys_last;i++){key=keys[i]===''?cur.length:keys[i];cur=cur[key]=i<keys_last?cur[key]||(keys[i+1]&&isNaN(keys[i+1])?{}:[]):val;}}else{if($.isArray(obj[key])){obj[key].push(val);}else if(obj[key]!==undefined){obj[key]=[obj[key],val];}else{obj[key]=val;}}}else if(key){obj[key]=coerce?undefined:'';}});return obj;};function jq_deparam_sub(is_fragment,url_or_params,coerce){if(url_or_params===undefined||typeof url_or_params==='boolean'){coerce=url_or_params;url_or_params=jq_param[is_fragment?str_fragment:str_querystring]();}else{url_or_params=is_string(url_or_params)?url_or_params.replace(is_fragment?re_trim_fragment:re_trim_querystring,''):url_or_params;}
return jq_deparam(url_or_params,coerce);};jq_deparam[str_querystring]=curry(jq_deparam_sub,0);jq_deparam[str_fragment]=jq_deparam_fragment=curry(jq_deparam_sub,1);$[str_elemUrlAttr]||($[str_elemUrlAttr]=function(obj){return $.extend(elemUrlAttr_cache,obj);})({a:str_href,base:str_href,iframe:str_src,img:str_src,input:str_src,form:'action',link:str_href,script:str_src});jq_elemUrlAttr=$[str_elemUrlAttr];function jq_fn_sub(mode,force_attr,params,merge_mode){if(!is_string(params)&&typeof params!=='object'){merge_mode=params;params=force_attr;force_attr=undefined;}
return this.each(function(){var that=$(this),attr=force_attr||jq_elemUrlAttr()[(this.nodeName||'').toLowerCase()]||'',url=attr&&that.attr(attr)||'';that.attr(attr,jq_param[mode](url,params,merge_mode));});};$.fn[str_querystring]=curry(jq_fn_sub,str_querystring);$.fn[str_fragment]=curry(jq_fn_sub,str_fragment);jq_bbq.pushState=jq_bbq_pushState=function(params,merge_mode){if(is_string(params)&&/^#/.test(params)&&merge_mode===undefined){merge_mode=2;}
var has_args=params!==undefined,url=jq_param_fragment(window[str_location][str_href],has_args?params:{},has_args?merge_mode:2);window[str_location][str_href]=url+(/#/.test(url)?'':'#');};jq_bbq.getState=jq_bbq_getState=function(key,coerce){return key===undefined||typeof key==='boolean'?jq_deparam_fragment(key):jq_deparam_fragment(coerce)[key];};jq_bbq.removeState=function(arr){var state={};if(arr!==undefined){state=jq_bbq_getState();$.each($.isArray(arr)?arr:arguments,function(i,v){delete state[v];});}
jq_bbq_pushState(state,2);};jq_event_special[str_hashchange]=$.extend(jq_event_special[str_hashchange],{add:function(handleObj){var old_handler;function new_handler(e){var hash=e[str_fragment]=jq_param_fragment();e.getState=function(key,coerce){return key===undefined||typeof key==='boolean'?jq_deparam(hash,key):jq_deparam(hash,coerce)[key];};old_handler.apply(this,arguments);};if($.isFunction(handleObj)){old_handler=handleObj;return new_handler;}else{old_handler=handleObj.handler;handleObj.handler=new_handler;}}});})(jQuery,this);(function($,window,undefined){'$:nomunge';var fake_onhashchange,jq_event_special=$.event.special,str_location='location',str_hashchange='hashchange',str_href='href',browser=$.browser,mode=document.documentMode,is_old_ie=browser.msie&&(mode===undefined||mode<8),supports_onhashchange='on'+str_hashchange in window&&!is_old_ie;function get_fragment(url){url=url||window[str_location][str_href];return url.replace(/^[^#]*#?(.*)$/,'$1');};$[str_hashchange+'Delay']=100;jq_event_special[str_hashchange]=$.extend(jq_event_special[str_hashchange],{setup:function(){if(supports_onhashchange){return false;}
$(fake_onhashchange.start);},teardown:function(){if(supports_onhashchange){return false;}
$(fake_onhashchange.stop);}});fake_onhashchange=(function(){var self={},timeout_id,iframe,set_history,get_history;function init(){set_history=get_history=function(val){return val;};if(is_old_ie){iframe=$('<iframe src="javascript:0"/>').hide().insertAfter('body')[0].contentWindow;get_history=function(){return get_fragment(iframe.document[str_location][str_href]);};set_history=function(hash,history_hash){if(hash!==history_hash){var doc=iframe.document;doc.open().close();doc[str_location].hash='#'+hash;}};set_history(get_fragment());}};self.start=function(){if(timeout_id){return;}
var last_hash=get_fragment();set_history||init();(function loopy(){var hash=get_fragment(),history_hash=get_history(last_hash);if(hash!==last_hash){set_history(last_hash=hash,history_hash);$(window).trigger(str_hashchange);}else if(history_hash!==last_hash){window[str_location][str_href]=window[str_location][str_href].replace(/#.*/,'')+'#'+history_hash;}
timeout_id=setTimeout(loopy,$[str_hashchange+'Delay']);})();};self.stop=function(){if(!iframe){timeout_id&&clearTimeout(timeout_id);timeout_id=0;}};return self;})();})(jQuery,this);$(function(){addWatchFunctionality();$('.pane').delegate('.sm-request-company','click',function(e){requestNewCompany($(this,e),e);});});function addWatchFunctionality(){$('.sm-watch-toggle').unbind('mouseenter');$('.sm-watch-toggle').unbind('mouseleave');$('.sm-watch-unwatch-form').unbind('submit');$('.sm-watch-toggle').mouseenter(function(e){var el=$(e.target);el.html(el.attr('hoveralt'));});$('.sm-watch-toggle').mouseleave(function(e){var el=$(e.target);el.html(el.attr('defaultalt'));});$('.sm-watch-unwatch-form').submit(function(e){e.preventDefault();var formEl=$(e.target);var action=formEl.attr('action');var data=formEl.serialize();var slugToWatch=$('.sm-watch-slug',formEl).val();$('BUTTON',formEl).attr('disabled','disabled');$.post(getContextualAjaxUrl(action),data,function(response){var button=formEl.find('BUTTON');currentText=button.html();newAction=formEl.attr('alt');formEl.attr('action',newAction);formEl.attr('alt',action);allButtons=$('BUTTON[rel='+button.attr('rel')+']');if(button.hasClass('sm-watch-button')){newText=button.attr('changealt');newHover=button.attr('clickalt');newClick=button.attr('defaultalt');allButtons.removeClass("sm-watch-button");allButtons.addClass("sm-unwatch-button");}else{newText=button.attr('clickalt');newHover=button.attr('watchalt');newClick=button.attr('hoveralt');allButtons.removeClass("sm-unwatch-button");allButtons.addClass("sm-watch-button");}
trackEvent(action.substring(1)+"/"+slugToWatch);allButtons.attr('hoveralt',newHover);allButtons.attr('clickalt',newClick);allButtons.attr('defaultalt',newText);allButtons.html(newText);button.removeAttr('disabled');});});}